version: 2

models:
  - name: gear_overview
    description: |
      Complete overview of all gear with usage statistics and lifecycle metrics.
      This is the primary analytics table combining gear details with cumulative usage data.
      Includes derived metrics like percentage of maximum distance used and remaining gear life.
    columns:
      - name: gear_id
        description: Unique identifier for each piece of gear (UUID from Garmin)
        data_tests:
          - unique
          - not_null
      
      - name: gear_type
        description: Type of gear (e.g., shoes, bike, etc.)
        data_tests:
          - not_null
      
      - name: gear_name
        description: Custom name or model description for the gear
      
      - name: status
        description: Current status of the gear (active or retired)
        data_tests:
          - accepted_values:
              values: ['active', 'retired']
      
      - name: start_date
        description: Date when the gear was first used (YYYY-MM-DD format)
        data_tests:
          - not_null
      
      - name: end_date
        description: Date when the gear was retired (NULL if still active)
      
      - name: stats_last_updated
        description: Last date when usage statistics were updated from Garmin
      
      - name: total_distance_km
        description: Cumulative distance traveled with this gear in kilometers
        data_tests:
          - not_null
      
      - name: total_activities
        description: Total number of activities recorded with this gear
        data_tests:
          - not_null
      
      - name: max_distance_km
        description: Maximum recommended distance in kilometers before gear retirement (NULL for gear without distance limits)
      
      - name: pct_of_max_distance_used
        description: Percentage of maximum recommended distance already used (NULL if no max distance defined)
      
      - name: remaining_distance_km
        description: Estimated kilometers remaining before retirement recommendation (NULL if no max distance defined)
      
      - name: days_since_first_use
        description: Number of days since the gear was first used
        data_tests:
          - not_null
      
      - name: dbt_loaded_at
        description: Timestamp when dbt processed this record

  - name: activity_summary
    description: |
      Activity summary table with weather and gear context.
      This mart uses the intermediate layer (int_activities_enriched) to provide
      a clean, business-ready view of activity performance including environmental conditions.
    columns:
      - name: activity_id
        description: Unique identifier for each activity
        data_tests:
          - unique
          - not_null

      - name: activity_name
        description: User-provided name for the activity

      - name: activity_type_key
        description: Type of activity (e.g., running, cycling)

      - name: start_date
        description: Date when the activity started
        data_tests:
          - not_null

      - name: distance_km
        description: Total distance covered in kilometers
        data_tests:
          - not_null

      - name: duration_minutes
        description: Total duration of the activity in minutes

      - name: avg_speed_kmh
        description: Average speed in kilometers per hour

      - name: total_calories
        description: Total calories burned during the activity

      - name: distance_category
        description: Categorized distance range (e.g., '5K-10K', '10K-15K', '20K+')
        data_tests:
          - not_null
          - accepted_values:
              values: ['Short Run', '1K-5K', '5K-10K', '10K-15K', '15K-20K', '20K+']

      - name: temperature_category
        description: Temperature condition category (Hot, Moderate, Cool, Cold)
        data_tests:
          - accepted_values:
              values: ['Hot', 'Moderate', 'Cool', 'Cold']

      - name: weather_condition
        description: Weather condition during the activity

      - name: gear_name
        description: Name of the gear used for this activity

  - name: activity_kpis_monthly
    description: |
      Monthly KPI metrics aggregated by activity category for dashboard cards.
      Pre-aggregated data showing activity counts, duration, distance, and calories
      grouped by year-month and activity category (Running, Cycling, Swimming, Strength, Multi-Sport, Other).
    columns:
      - name: year_month
        description: Year and month in YYYY-MM format (e.g., '2024-11')
        data_tests:
          - not_null

      - name: year
        description: Year as integer (e.g., 2024)
        data_tests:
          - not_null

      - name: month
        description: Month as integer (1-12)
        data_tests:
          - not_null

      - name: activity_category
        description: Grouped activity category
        data_tests:
          - not_null
          - accepted_values:
              values: ['Running', 'Cycling', 'Swimming', 'Strength', 'Multi-Sport', 'Other']

      - name: activity_count
        description: Number of activities in this category for the month
        data_tests:
          - not_null

      - name: total_duration_minutes
        description: Total time spent on activities in minutes (e.g., 416.8)
        data_tests:
          - not_null

      - name: total_duration_hours
        description: Total time spent on activities in hours (decimal format, e.g., 7.7)
        data_tests:
          - not_null

      - name: total_duration_hours_whole
        description: Whole hours component of total duration (e.g., 7 from 7h 45m)
        data_tests:
          - not_null

      - name: total_duration_minutes_remainder
        description: Minutes component of total duration (e.g., 45 from 7h 45m)
        data_tests:
          - not_null

      - name: total_duration_formatted
        description: Human-readable duration format (e.g., '7h 45m')
        data_tests:
          - not_null

      - name: avg_duration_minutes
        description: Average duration per activity in minutes

      - name: total_distance_km
        description: Total distance covered in kilometers (sum of all activities)

      - name: avg_distance_km
        description: Average distance per activity in kilometers (excluding zero-distance activities)

      - name: total_calories
        description: Total calories burned across all activities

      - name: avg_calories
        description: Average calories burned per activity

      - name: dbt_loaded_at
        description: Timestamp when dbt processed this record

  - name: activity_daily_summary
    description: |
      Daily activity summary for calendar heatmap visualization.
      One row per date with simple aggregated metrics for ALL activity types.
      Includes strength training and all non-distance activities.
    columns:
      - name: activity_date
        description: Date of activities (YYYY-MM-DD format)
        data_tests:
          - unique
          - not_null

      - name: year
        description: Year as integer (e.g., 2024)
        data_tests:
          - not_null

      - name: month
        description: Month as integer (1-12)
        data_tests:
          - not_null

      - name: day
        description: Day of month as integer (1-31)
        data_tests:
          - not_null

      - name: day_of_week
        description: Day of week (0=Sunday, 1=Monday, ..., 6=Saturday)
        data_tests:
          - not_null

      - name: total_duration_minutes
        description: Total time spent on all activities in minutes (used for heatmap color intensity)
        data_tests:
          - not_null

      - name: total_duration_formatted
        description: Human-readable duration format for tooltips (e.g., '1h 30m')
        data_tests:
          - not_null

      - name: total_distance_km
        description: Total distance covered across all activities in kilometers
        data_tests:
          - not_null

      - name: total_calories
        description: Total calories burned across all activities
        data_tests:
          - not_null

      - name: dbt_loaded_at
        description: Timestamp when dbt processed this record

  - name: activity_details
    description: |
      Detailed activity view with comprehensive metrics and categorization.
      This mart provides all activity details for filterable data tables and detailed exploration.
      Includes the same activity categorization as the KPI dashboard for consistency.
      One row per activity with all performance, weather, and gear information.
    columns:
      - name: activity_id
        description: Unique identifier for each activity
        data_tests:
          - unique
          - not_null

      - name: activity_name
        description: User-provided name for the activity

      - name: activity_type_key
        description: Specific activity type (e.g., running, cycling, trail_running)
        data_tests:
          - not_null

      - name: activity_category
        description: Grouped activity category matching KPI dashboard
        data_tests:
          - not_null
          - accepted_values:
              values: ['Running', 'Cycling', 'Swimming', 'Strength', 'Multi-Sport', 'Other']

      - name: start_date
        description: Date and time when the activity started
        data_tests:
          - not_null

      - name: year
        description: Year as integer (e.g., 2024)
        data_tests:
          - not_null

      - name: month
        description: Month as integer (1-12)
        data_tests:
          - not_null

      - name: day
        description: Day of month as integer (1-31)
        data_tests:
          - not_null

      - name: year_month
        description: Year and month in YYYY-MM format (e.g., '2024-11')
        data_tests:
          - not_null

      - name: day_of_week
        description: Day of week name (Monday, Tuesday, etc.)
        data_tests:
          - not_null

      - name: distance_km
        description: Total distance covered in kilometers
        data_tests:
          - not_null

      - name: duration_minutes
        description: Total duration of the activity in minutes
        data_tests:
          - not_null

      - name: duration_formatted
        description: Human-readable duration format (e.g., '1h 30m')
        data_tests:
          - not_null

      - name: avg_speed_kmh
        description: Average speed in kilometers per hour

      - name: avg_pace_formatted
        description: Average pace formatted as minutes per kilometer

      - name: elevation_gain_m
        description: Total elevation gain in meters

      - name: total_calories
        description: Total calories burned during the activity

      - name: avg_heart_rate
        description: Average heart rate in beats per minute

      - name: max_heart_rate
        description: Maximum heart rate in beats per minute

      - name: aerobic_training_effect
        description: Aerobic training effect score

      - name: anaerobic_training_effect
        description: Anaerobic training effect score

      - name: temperature_c
        description: Temperature in Celsius during the activity

      - name: feels_like_c
        description: Feels-like temperature in Celsius

      - name: weather_condition
        description: Weather condition during the activity

      - name: wind_speed_kmh
        description: Wind speed in kilometers per hour

      - name: distance_category
        description: Categorized distance range (includes 'No distance recorded' for strength training and other non-distance activities)
        data_tests:
          - not_null
          - accepted_values:
              values: ['No distance recorded', 'Under 1K', '1K-5K', '5K-10K', '10K-15K', '15K-20K', '20K+']

      - name: temperature_category
        description: Temperature condition category
        data_tests:
          - accepted_values:
              values: ['Hot', 'Moderate', 'Cool', 'Cold']

      - name: gear_name
        description: Name of the gear used for this activity

      - name: dbt_loaded_at
        description: Timestamp when dbt processed this record